[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
buffer = { path = "../buffer/" }
thiserror = "2.0.12"
utils = { path = "../utils/" }
uuid = { version = "1.17.0", features = ["v4"] }
